### ISSUE TITLE
NullPointerException: The buildXml parameter cannot be null

### ISSUE THREAD

**Issue by laubrino** [tusharjoshi/nbrunwithargs#3]
When I try to run a file with this plugin I get NPE. I reported the crash through Nebeans 8, see https://netbeans.org/bugzilla/show_bug.cgi?id=243737

The file is a part of a maven project, so maybe this is the problem (?)

**Comment by gmcruz** [comment]
I just downloaded this plugin on two different machines and get the same issue "The buildXml parameter cannot be null"
BOTH MACHINES
Maven project
Win 7 PRO
Netbeans 8
Java7

Does anyone have a clue on this?

**Comment by tusharvjoshi** [comment]
This plugin was written for ANT based Java projects, and needs changes to avoid showing menus in Maven project or / and add more functionality to use it in Maven projects.

**Comment by kkofler** [comment]
Since I have not received an answer to my pull request for more than 5 months now, I have uploaded a release to my fork:
https://github.com/kkofler/nbrunwithargs/releases/tag/3.0
The uploaded binary has been tested by me and by a few of my colleagues. It should work with NetBeans ≥ 8.0.

If I make further improvements/fixes, you will find them under: https://github.com/kkofler/nbrunwithargs/releases
